---
name: module4_task0
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

jobs:
  module4_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker run
        run: |
          cd module4_task0/
          docker build -t my-app .
          docker run -dp 80:80 my-app