---
name: module3_task2
on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: 8 8 * * *
jobs:
  module3_task2:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone and check out repository
        uses: actions/checkout@v3

      - name: Run setup script to install Hugo
        run: |
          cd module3_task2/
          sudo ./setup.sh
        shell: bash

      - name: lint
        run: |
          cd module3_task2/
          make lint

      - name: Use build in Makefile
        run: |
          cd module3_task2/
          sudo make build

      - name: Build and create the package
        run: |
         sudo make -C module3_task2/ package

      - name: post
        run: |
          cd module3_task2/
          make POST_TITLE="Test Title" POST_NAME="Test-name" post

      - name: archive build
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task2/awesome-website.zip
