---
name: module4_task1

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Navigate to project directory
        run: |
          cd module4_task1/
          make help
